import Head from 'next/head'
const Header = () => {
    return ( 
        <Head>
        <title>To Do App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
     );
}
 
export default Header;